### ISSUE TITLE
Chapter 5: zap-baseline-scan

### ISSUE THREAD

**Issue by bwearp** [PacktPublishing/Security-Automation-with-Ansible-2#3]
Hi,

I am getting the error: "'auto_remove' is not compatible with docker-py, and requires the docker python module"

Any ideas?

**Comment by madhuakula** [comment]
Looks like API issue. As per the Ansible docs, they have added in 2.4
http://docs.ansible.com/ansible/latest/modules/docker_container_module.html

Try checking the requirements met perfectly as per Ansible docs?

```
python >= 2.6
docker-py >= 1.7.0
Docker API >= 1.20
```
I will check once again if any other issues.

Thanks for letting us know :)

**Comment by bwearp** [comment]
I am using all the latest versions, as I installed them using the other playbooks in the free chapter 5.

1. https://github.com/madhuakula/security-automation-with-ansible-2/blob/master/chapter-5/docker/site.yml
2. https://github.com/madhuakula/security-automation-with-ansible-2/blob/master/chapter-5/zap-setup-playbook/site.yml

Is that not the correct thing to do?

**Comment by ManikandanKurup-Packt** [comment]
Hi, I hope the issue has been resolved. If not, please reopen this issue.

**Comment by madhuakula** [comment]
Hey @bwearp 

I am really sorry to see the delay in response. I think the Ansible module for Docker has changed quite a lot. Please feel free to check now and let me know if you still face any issues.
